config/routes.rb
Rails.application.routes.draw do
  root to: "catalogs#index"

  get '/signin', to: 'sessions#new', as: 'signin'
  get '/signup', to: 'users#new', as: 'signup'
  post '/signin', to: 'sessions#create'

  resources :authors, :publishers, :books
  resources :users, only: [:index, :show, :new, :create]
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :publications, dependent: :destroy
  has_many :books, through: :publications

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :publisher
  has_many :authors, through: :publications
  has_many :publications, dependent: :destroy
  validates :title, presence: true
  validates :isbn, presence: true
  validates :description, presence: true
  validates :published_at, presence: true
  validates :publisher_id, presence: true
  validates :page_count, numericality: { only_integer: true, greater_than: 0 }
  validates :price, numericality: { greater_than_or_equal_to: 0.0 }

  mount_uploader :book_cover, BookCoverUploader
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :author
  belongs_to :book
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books
  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false },
            format: { with: /\A[A-Z0-9#_-~!$&'()*+,;=:.%]+@[A-Z0-9.-]+\.[A-Z]{2,4}\z/i }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, except: [:index, :new, :create]
  def index

  end

  def show
    # require 'pry'; binding.pry
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      flash[:success] = "Author has been created"
      redirect_to @author
    else
      flash[:danger] = "Author has not been created"
      render :new
    end
  end

  def edit
  end

  def update
    if @author.update(author_params)
      flash[:success] = "Author has been updated"
      redirect_to @author
    else
      flash[:danger] = "Author has not been updated"
      render :edit
    end
  end

  def destroy
    @author.destroy
    flash[:success] = "Author has been deleted"
    redirect_to authors_path
  end

  private

  def author_params
    params.require(:author).permit(:first_name,:last_name)
  end

  def set_author
    @author = Author.find(params[:id])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, except: [:index, :new, :create]
  def index

  end

  def show
    # require 'pry'; binding.pry
  end

  def new
    @book = Book.new
    @publisher = Publisher.all
    @authors = Author.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:success] = "Book has been created"
      redirect_to @book
    else
      flash[:danger] = "Book has not been created"
      @publisher = Publisher.all
      @authors = Author.all
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      flash[:success] = "Book has been updated"
      redirect_to @book
    else
      flash[:danger] = "Book has not been updated"
      @publisher = Publisher.all
      @authors = Author.all
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:success] = "Book has been deleted"
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :price, :isbn, :page_count, :description,
                                 :published_at, :publisher_id, :book_cover, :author_ids => [])
  end

  def set_book
    @book = Book.find(params[:id])
  end

end

app/controllers/concerns/catalogs_controller.rb
class CatalogsController < ApplicationController
  def index

  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, except: [:index, :new, :create]
  def index

  end

  def show
    # require 'pry'; binding.pry
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
    if @publisher.save
      flash[:success] = "Publisher has been created"
      redirect_to @publisher
    else
      flash[:danger] = "Publisher has not been created"
      render :new
    end
  end

  def edit
  end

  def update
    if @publisher.update(publisher_params)
      flash[:success] = "Publisher has been updated"
      redirect_to @publisher
    else
      flash[:danger] = "Publisher has not been updated"
      render :edit
    end
  end

  def destroy
    @publisher.destroy
    flash[:success] = "Publisher has been deleted"
    redirect_to publishers_path
  end

  private

  def publisher_params
    params.require(:publisher).permit(:name)
  end

  def set_publisher
    @publisher = Publisher.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if current_user
  end

  def create
    user = User.find_by_email(params['email'])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Sign in Successful"
      redirect_to root_path
    else
      flash[:danger] = "Invalid email/password combination"
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
    @users = User.all
  end

  def show

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'User has been created'
      redirect_to @user
    else
      flash[:danger] = 'User has not been created'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/authors/_form.html.erb
<%= bootstrap_form_for( @author, :html => {class: 'form-horizontal'}) do |f| %>
    <div class="form-group">
      <label class="control-label col-md-3" for="First name">First name</label>
      <div class="col-md-9">
        <%= f.text_field :first_name,class: 'form-control',hide_label: true %>
      </div>
    </div>

    <div class="form-group">
      <label class="control-label col-md-3" for="Last name">Last name</label>
      <div class="col-md-9">
        <%= f.text_field :last_name,class: 'form-control',hide_label: true %>
      </div>
    </div>

    <div class="form-group actions control-group">
      <div class="col-md-offset-3">
        <%= f.submit class: 'btn btn-primary'%>
      </div>
    </div>
<% end %>

app/views/books/_form.html.erb
<%= bootstrap_form_for( @book, layout: :horizontal, :html => {class: 'form-horizontal'}) do |f| %>
    <%= f.text_field :title, placeholder: 'Title of the book', autofocus: true %>
    <%= f.text_field :isbn, placeholder: 'Book ISBN' %>
    <%= f.number_field :page_count, placeholder: 'Number Pages' %>
    <%= f.number_field :price, placeholder: 'Book unit price' %>
    <%= f.date_field :published_at, label: 'Published at'  %>
    <%= f.text_area :description, placeholder: 'Book description' %>
    <%= f.select :publisher_id, @publisher.map { |p| [p.name,p.id]},
                    prompt: 'Select a publisher'%>
    <%= f.file_field :book_cover %>
    <%= f.collection_check_boxes :author_ids, @authors, :id, :full_name %>
    <%= f.submit %>
<% end %>

app/views/books/edit.html.erb
<div class="row">
  <h3 class="titles">Edit Author</h3>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/books/index.html.erb
<%= link_to 'Add New book', new_book_path%>

app/views/books/new.html.erb
<div class="row">
  <h3 class="titles">Add New Author</h3>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/catalogs/index.html.erb
<h1>Catalog Index Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bookstore App</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/header' %>

  <%= render 'shared/main' %>

  <%= render 'shared/footer' %>

</body>
</html>

app/views/publishers/_form.html.erb
<%= bootstrap_form_for( @publisher, :html => {class: 'form-horizontal'}) do |f| %>
    <div class="form-group">
      <label class="control-label col-md-3" for="Name">Name</label>
      <div class="col-md-9">
        <%= f.text_field :name,class: 'form-control',hide_label: true %>
      </div>
    </div>

    <div class="form-group actions control-group">
      <div class="col-md-offset-3">
        <%= f.submit class: 'btn btn-primary'%>
      </div>
    </div>
<% end %>

app/views/publishers/edit.html.erb
<div class="row">
  <h3 class="titles">Edit Publisher</h3>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/publishers/index.html.erb
<h1>This is the index page of publishers controller</h1>

app/views/publishers/new.html.erb
<div class="row">
  <h3 class="titles">Add New Publisher</h3>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <footer role="contentinfo">
        <p class="text-center">
          <small>Copyright &copy; Islam,Tawhid-al</small>
        </p>
      </footer>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <%= link_to "Bookstore App", '#',class: 'navbar-brand'%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home',root_path%></li>
        <li><%= link_to 'Authors', authors_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <li><%= link_to 'Books', books_path %></li>
        <li><%= link_to 'Sign up', new_user_path %></li>
        <li><%= link_to 'Sign in', signin_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_main.html.erb
<main role="main">
  <div class="container">
    <%= render  'shared/message' %>
    <div class="row">
      <div class="col-md-9">
        <% if content_for?(:sidebar) %>
            <div class="col-md-3">
              <%= yield :sidebar %>
            </div>
            <div class="col-md-9">
              <%= yield %>
            </div>
        <% else %>
            <div class="col-md-10 col-md-offset-1">
              <%= yield %>
            </div>
        <% end %>
      </div>
      <div class="col-md-3">
        <div id="cart">

        </div>
      </div>
    </div>
  </div>
</main>

app/views/shared/_message.html.erb
<% flash.each do |name,msg| %>
    <div class="alert alert-<%= "#{name}" %>">
      <a class="close" href="#" data-dismiss='alert'>&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= bootstrap_form_for( @user, layout: :horizontal, :html => {class: 'form-horizontal'}) do |f| %>
    <%= f.text_field :first_name, placeholder: 'First Name', autofocus: true %>
    <%= f.text_field :last_name, placeholder: 'Last Name' %>
    <%= f.email_field :email, placeholder: 'Email' %>
    <%= f.password_field :password, placeholder: 'Enter Password', label: 'Password',for: 'user_password_confirmation' %>
    <%= f.password_field :password_confirmation, placeholder: 'Enter Password again', label: 'Confirmation' %>
    <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
    <%= link_to user.email, user %>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <h3 class="titles">Add New User</h3>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<section>
  <div class="col-sm-10 col-sm-offset-1">
    <header>
      <h3 class="titles"><%= "#{@user.full_name}" %></h3>
    </header>
    <p id="first-name">First name: <%= @user.first_name %></p>
    <p id="last-name">Last name: <%= @user.last_name %></p>
    <p id="email">Email: <%= @user.email %></p>
  </div>
</section>